Repository sDev67/projet_git, pull requests merged in 2022-11, with the labels that each got.

#2 Create LICENSE
  LICENSE
Labels: documentation

#7 Feature/javascript framework
  .gitignore
  docker-compose.yml
  package-lock.json
  package.json
  sources/index.html
  sources/js/script.js
  sources/scss/styles.scss
  vite.config.js
Labels: enhancement

#11 Add linter and cypress
  .eslintrc.json
  cypress.config.js
  cypress/e2e/app.cy.js
  package-lock.json
  package.json
  sources/js/script.js
  vite.config.js
Labels: enhancement

#13 Hotfix : Add supportfiles to false.
  cypress.config.js
  sources/js/script.js
Labels: bug

#12 Create node.js.yml
  .github/workflows/node.js.yml
  sources/js/script.js
Labels: enhancement

#14 Create static.yml
  .github/workflows/static.yml
Labels: enhancement

#15 Add hook for linter
  .githooks/pre-commit
  package-lock.json
  package.json
  sources/css/style.css
  sources/css/style.css.map
Labels: enhancement

#23 Update the contributing
  .github/CONTRIBUTING.md
Labels: documentation

#17 Update README.md
  .githooks/.pre-push
  .githooks/commit-msg
  .github/CONTRIBUTING.md
  LICENSE
  README.md
  images/screen_branch.PNG
  images/screen_new_gpg_key.PNG
  images/screen_new_rule.PNG
  images/screen_onglet_ssh_gpg.PNG
  images/screen_repo_setting.PNG
  images/screen_setting.PNG
Labels: documentation
